# Generated by Django 2.2.9 on 2020-05-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
                ('proof', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
                ('start_booking', models.DateField()),
                ('end_booking', models.DateField()),
                ('preferences', models.CharField(max_length=1000)),
            ],
        ),
    ]
